name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - anyio=4.9.0
  - aom=3.9.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - catalogue=2.0.10
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.21.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - confection=0.1.5
  - contourpy=1.3.1
  - cpython=3.10.16
  - cycler=0.12.1
  - cymem=2.0.11
  - cython-blis=1.0.1
  - dav1d=1.2.1
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - fastai=2.7.19
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - fastcore=1.7.20
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - filelock=3.18.0
  - fonttools=4.56.0
  - freetype=2.13.3
  - fsspec=2025.3.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.6
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - langcodes=3.3.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx
  - libde265=1.0.15
  - libdeflate=1.23
  - libffi=3.4.2
  - libgfortran
  - libgfortran5=14.2.0
  - libheif=1.19.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - murmurhash=1.0.10
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=2.2.4
  - openjpeg=2.5.3
  - openssl=3.4.1
  - optree=0.14.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0.1
  - preshed=3.0.9
  - pthread-stubs=0.4
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - rav1e=0.6.6
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.2
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - smart-open=7.1.0
  - smart_open=7.1.0
  - sniffio=1.3.1
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.1
  - starlette=0.46.1
  - svt-av1=3.0.2
  - sympy=1.13.3
  - thinc=8.3.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.1
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.13.0
  - typing_extensions=4.13.0
  - tzdata=2025b
  - ujson=5.10.0
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - wasabi=1.1.3
  - watchfiles=1.0.4
  - weasel=0.4.1
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.2
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
